spring.application.name=payment-service
server.port=8084

# Cấu hình URL của Order Service để thực hiện lệnh gọi liên dịch vụ
order-service.url=http://192.168.137.12:8083

# CORS (Allowed from Frontend)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*

# CORS (Allowed from Frontend)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*

# H2 Database Configuration
# Dịch vụ nội bộ sẽ chạy trực tiếp vào file. Các dịch vụ khác sẽ gọi qua TCP.
spring.datasource.url=jdbc:h2:file:./data/minifood;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

